### ISSUE TITLE
cool tool

### ISSUE THREAD

**Issue by fabio1999ita** [bsangmin/sc-player#1]
nice tool, are you able to find the lagger inside the lobby of game and show it inside the tool?

**Comment by bsangmin** [comment]
I'm sorry for the late comment. 
Actually I stopped this project. But I recommand [kLauncher](https://klauncher.kr/), this project is similar to sc-player, many korean SC users using this.
Thanks.

**Comment by fabio1999ita** [comment]
can you publish full code?
